project:
  type: website

website:
  title: "Blind Student Aid AI"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: BlindStudentAid.ipynb
        text: Project Notebook
    right:
      - icon: github
        href: https://github.com/RohanRanshinge/blind-student-aid-ai

format:
  html:
    theme: cosmo
    toc: true
    code-fold: show
    code-tools: true

execute:
  enabled: false
